# Confidence Intervals

In [93]:
# Libraries

import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns
import random as rand

## Challenge 1
We want to estimate the average size of the men of a country with a confidence level of 80%. Assuming that the standard deviation of the sizes in the population is 4, get the confidence interval with a sample of men selected randomly, whose heights are:

````
heights = [167, 167, 168, 168, 168, 169, 171, 172, 173, 175, 175, 175, 177, 182, 195]
````

**Hint**: function `stats.norm.interval` from `scipy` can help you get through this exercise. 

**Summary of the exercise**

- Average size of the mean of a country = ?
- Confidence level = 0.80%
- Standard deviation of the sizes in the population = 4


##### Question = confidence interval with a sample of men selected randomly?

- Formula: st.norm.interval(c, loc=mean, scale = sigma/np.sqrt(n))

In [94]:
heights = [167, 167, 168, 168, 168, 169, 171, 172, 173, 175, 175, 175, 177, 182, 195]
heights

[167, 167, 168, 168, 168, 169, 171, 172, 173, 175, 175, 175, 177, 182, 195]

In [95]:
heights_df = pd.DataFrame(heights, columns=['heights'])
heights_df

heights
0       167
1       167
2       168
3       168
4       168
5       169
6       171
7       172
8       173
9       175
10      175
11      175
12      177
13      182
14      195

##### Calculate the confidence interval with the std of the sample of 15 men

In [96]:
# Mean of the sample

x = heights_df['heights'].mean()
x

173.46666666666667

In [97]:
# Confidence level of the sample

c = 0.80

In [98]:
# Standard Deviation of our population

sigma = 4

In [99]:
# The number of elements in our sample

n= len(heights_df)
n

15

In [100]:
# Calculate the confidence interval with PYTHON, where:

st.norm.interval(c, loc=x, scale = sigma/np.sqrt(n))

(172.14308590115726, 174.79024743217607)

## Challenge 2 
In a sample of 105 shops selected randomly from an area, we note that 27 of them have had losses in this month. Get an interval for the proportion of businesses in the area with losses to a confidence level of 80% and a confidence level of 90%.

**Hint**: function `stats.norm.interval` from `scipy` can help you get through this exercise. 

**Summary of the exercise**

- Confidence level 1 = 0.80%
- Confidence level 2 = 0.90%
- N = size of sample = 105 shops
    - 27 shops with losses
    - 78 shops with profits
- Average size of the mean of 27 shops with losses = ?
- Standard deviation of the sizes in the population = ?


##### Question = confidence interval with a sample of 27 shops

- Formula: st.norm.interval(c, loc=mean, scale = sigma/np.sqrt(n))

### Option 1

**Formula of sigma**
1) np.sqrt((x_i - mu)^2/n)

2) np.sqrt(mu*(1-mu))

sigma = population standard deviation
N	=	the size of the population
x_i	=	each value from the population
mu	=	the population mean

In [101]:
# The number of elements in our sample

n= 105

In [102]:
# Confidence level of our sample of 27 shops

c_1 = 0.80
c_2 = 0.90

In [103]:
# Mean of the sample of 27 shops

x_losses = 27/n
x_losses

0.2571428571428571

In [107]:
# Standard Deviation of our sample

sigma_opt1 = np.sqrt(x_losses*(1-x_losses))
sigma_opt1


0.4370588154508101

In [108]:
# Calculate the confidence interval with c_1 with PYTHON, where:

st.norm.interval(c_1, loc=x_losses, scale = sigma_opt1/np.sqrt(n))

(0.20248138545542083, 0.3118043288302934)

In [110]:
# Calculate the confidence interval with c_2 with PYTHON, where:

st.norm.interval(c_2, loc=x_losses, scale = sigma_opt1/np.sqrt(n))

(0.1869856177645281, 0.32730009652118613)

### Option 2

In [78]:
# Create an array of 78 zeroes, to indicate the shops with profits

profit = np.zeros((78,), dtype=int) 
profit

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
# Create an array of 27 ones, to indicate the shops with losses

losses = np.ones((27,), dtype=int)
losses

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [114]:
# Concatenate arrays profit and losses

shops = np.concatenate((profit, losses))
shops

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [115]:
# Convert array into a dataframe

shops_df = pd.DataFrame(shops, columns=['Profitable?'])
shops_df

#where 0 is profitable, whereas 1 is not profitable

Profitable?
0              0
1              0
2              0
3              0
4              0
..           ...
100            1
101            1
102            1
103            1
104            1

[105 rows x 1 columns]

##### Compute the confidence intervals, knowing that:

1) Confidence level 1 = 0.80%

2) Confidence level 2 = 0.90%

3) N = size of sample = 105 shops

4) Average size of the mean of 27 shops with losses = ?

5) Standard deviation of the sizes in the population = ?

6) Formula for confidence intervals is: st.norm.interval(c, loc=mean, scale = sigma/np.sqrt(n))

In [120]:
# 4. Mean of 27 shops

x_losses

0.2571428571428571

In [121]:
# 5. Standard Deviation of the size in our sample of 105 shops

sigma_opt2 = shops_df['Profitable?'].std(ddof=1)
sigma_opt2

0.43915503282684

In [122]:
# Calculate the confidence interval with c_1 with PYTHON, where:

st.norm.interval(c_1, loc=x_losses, scale = sigma_opt2/np.sqrt(n))

(0.20221921861951708, 0.31206649566619715)

In [123]:
# Calculate the confidence interval with c_2 with PYTHON, where:

st.norm.interval(c_2, loc=x_losses, scale = sigma_opt2/np.sqrt(n))

(0.18664913027350827, 0.32763658401220597)

## Bonus Challenge
The error level or sampling error for the first challenge is given by the following expression:
$$Error = z_{\frac{\alpha}{2}}\frac{\sigma}{\sqrt n}$$
Where z represents the value for N(0,1)


Suppose that with the previous data of challenge 1, and with a confidence level of
99% (that is, almost certainly) we want to estimate the average population size, so that the error level committed is not greater than half a centimeter.

#### 1.- Determine what size the selected sample of men should be.

In [ ]:
# your code here

#### 2.- For the second challenge, we have the following error:
$$ Error = z_{\frac{\alpha}{2}}\sqrt{\frac{p\times q}{n}} $$
#### Determine the sample size required to not exceed an error of 1% with a confidence of 80%.

In [ ]:
# your code here

## Bonus Challenge

Let's consider the following problem:

Build a confidence interval of 94% for the real difference between the durations of two brands of spotlights, if a sample of 40 spotlights taken randomly from the first mark gave an average duration of 418 hours, and a sample of 50 bulbs of another brand gave a duration average of 402 hours. The standard deviations of the two
populations are 26 hours and 22 hours, respectively.

Sometimes, we will be interested in the difference of two different groups of random variables. We can also build a confidence interval for that! We have some different cases regarding the variance but for this specific case (the variance are different and known), we have that:

$$\overline{X} - \overline{Y}  \sim N(\mu_{X} - \mu_{Y} , \sqrt{\frac{\sigma_{X}^2}{n_X}+\frac{\sigma_{Y}^2}{n_Y}})$$

Solve the problem with this information.

In [ ]:
# your code here